### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by jaredthirsk** [dmitry-shechtman/AsyncMvvm#1]
Is .NET Core supported?  If not, is it in the roadmap? (If so, perhaps the readme should be updated.)

**Comment by dmitry-shechtman** [comment]
There are currently no plans of supporting project.json. I believe it's worth waiting for the .csproj support as promised by Microsoft.

**Comment by dmitry-shechtman** [comment]
Ditto.AsyncMvvm v1.1.0 adds support for .NET Standard 1.0 and .NET Core 1.0.

Thank you for your interest.
